// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// IProfileController is an autogenerated mock type for the IProfileController type
type IProfileController struct {
	mock.Mock
}

// ControllerGetProfile provides a mock function with given fields: c
func (_m *IProfileController) ControllerGetProfile(c echo.Context) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for ControllerGetProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ControllerUpdateProfileName provides a mock function with given fields: c
func (_m *IProfileController) ControllerUpdateProfileName(c echo.Context) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for ControllerUpdateProfileName")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIProfileController creates a new instance of IProfileController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIProfileController(t interface {
	mock.TestingT
	Cleanup(func())
}) *IProfileController {
	mock := &IProfileController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
